// Global Icon Constants
const ICONS = {
	POETICS: "./images/icons/poetics.png",
	PLACEHOLDER: "./images/icons/placeholder.png",
};

// In-game item IDs for shared icons, used by assets/xivapi-icons.js to load
// the official icon from XIVAPI (the local PNG above stays as the fallback).
// Individual materials carry their own `itemId` on the data entry instead.
const ICON_ITEM_IDS = {
	[ICONS.POETICS]: 28, // Allagan Tomestone of Poetics
};

// Sources verified against Icy Veins' per-stage relic guides (Zodiac, Atma,
// Animus, Novus, Nexus), Console Games Wiki's Zodiac Weapons stage table,
// and FFXIV Guild's community walkthrough, Sept 2026. This is the original
// A Realm Reborn relic line: Relic -> Zenith -> Atma -> Animus -> Novus ->
// Nexus -> Zodiac Braves -> Zodiac Zeta. Several later stages (Nexus onward)
// are light/quest-gated rather than simple item turn-ins, so those are
// tracked as checklist milestones instead of exact material counts.
const ARR_DATA = [
	// --- STAGE 1: Relic (i80) ---
	{
		id: "base_relic",
		stage: "1. Relic (i80)",
		name: "Base Relic Weapon",
		type: "checklist",
		icon: "./images/icons/relic.png",
		qty: 1,
		tip: "Start with 'The Weaponsmith of Legend' (Vesper Bay) into 'A Relic Reborn' (Gerolt, North Shroud). Collect the Timeworn weapon, deliver a materia-melded weapon, clear the Chimera trial, run Amdapor Keep, defeat 24 beastmen, then clear Hydra + Ifrit/Garuda/Titan (Hard) unsynced.",
		tooltip: [
			"'The Weaponsmith of Legend' — Vesper Bay (12,14)",
			"'A Relic Reborn' — Gerolt, North Shroud (30,20)",
			"Deliver materia-melded weapon (2 materia of matching grade)",
			"Trial: 'A Relic Reborn: The Chimera' (soloable unsynced)",
			"Amdapor Keep (Normal)",
			"Defeat 24 beastmen at job-specific locations",
			"Clear Hydra, Ifrit (Hard), Garuda (Hard), Titan (Hard) unsynced",
		],
		options: [{ label: "Quest Complete", cost: 0, currency: "" }],
	},

	// --- STAGE 2: Zenith (i90) ---
	{
		id: "thavnairian_mist",
		stage: "2. Zenith (i90)",
		name: "Thavnairian Mist",
		type: "item",
		icon: "./images/icons/thavnairian-mist.png",
		itemId: 6268,
		qty: 3,
		tip: "With your base relic equipped, speak to Gerolt, then trade 3 Thavnairian Mist (bought with Poetics) at the Furnace to reforge into the Zenith weapon.",
		options: [{ label: "Poetics Vendor", cost: 0, currency: "" }],
	},

	// --- STAGE 3: Atma (i100) — 12 Atma, one per La Noscea/Thanalan/Shroud zone ---
	{
		id: "atma_lion",
		stage: "3. Atma (i100)",
		name: "Atma of the Lion",
		type: "item",
		icon: "./images/icons/atma.png",
		itemId: 7858,
		qty: 1,
		tip: "Outer La Noscea FATEs, Zenith weapon equipped. ~20% drop per completion; does not require good FATE performance.",
		options: [{ label: "FATE Completion", cost: 0, currency: "" }],
	},
	{
		id: "atma_water_bearer",
		stage: "3. Atma (i100)",
		name: "Atma of the Water-bearer",
		type: "item",
		icon: "./images/icons/atma.png",
		itemId: 7853,
		qty: 1,
		tip: "Upper La Noscea FATEs, Zenith weapon equipped.",
		options: [{ label: "FATE Completion", cost: 0, currency: "" }],
	},
	{
		id: "atma_ram",
		stage: "3. Atma (i100)",
		name: "Atma of the Ram",
		type: "item",
		icon: "./images/icons/atma.png",
		itemId: 7856,
		qty: 1,
		tip: "Middle La Noscea FATEs, Zenith weapon equipped.",
		options: [{ label: "FATE Completion", cost: 0, currency: "" }],
	},
	{
		id: "atma_crab",
		stage: "3. Atma (i100)",
		name: "Atma of the Crab",
		type: "item",
		icon: "./images/icons/atma.png",
		itemId: 7862,
		qty: 1,
		tip: "Western La Noscea FATEs, Zenith weapon equipped.",
		options: [{ label: "FATE Completion", cost: 0, currency: "" }],
	},
	{
		id: "atma_fish",
		stage: "3. Atma (i100)",
		name: "Atma of the Fish",
		type: "item",
		icon: "./images/icons/atma.png",
		itemId: 7859,
		qty: 1,
		tip: "Lower La Noscea FATEs, Zenith weapon equipped.",
		options: [{ label: "FATE Completion", cost: 0, currency: "" }],
	},
	{
		id: "atma_bull",
		stage: "3. Atma (i100)",
		name: "Atma of the Bull",
		type: "item",
		icon: "./images/icons/atma.png",
		itemId: 7855,
		qty: 1,
		tip: "Eastern Thanalan FATEs, Zenith weapon equipped.",
		options: [{ label: "FATE Completion", cost: 0, currency: "" }],
	},
	{
		id: "atma_scales",
		stage: "3. Atma (i100)",
		name: "Atma of the Scales",
		type: "item",
		icon: "./images/icons/atma.png",
		itemId: 7861,
		qty: 1,
		tip: "Central Thanalan FATEs, Zenith weapon equipped.",
		options: [{ label: "FATE Completion", cost: 0, currency: "" }],
	},
	{
		id: "atma_twins",
		stage: "3. Atma (i100)",
		name: "Atma of the Twins",
		type: "item",
		icon: "./images/icons/atma.png",
		itemId: 7857,
		qty: 1,
		tip: "Western Thanalan FATEs, Zenith weapon equipped.",
		options: [{ label: "FATE Completion", cost: 0, currency: "" }],
	},
	{
		id: "atma_scorpion",
		stage: "3. Atma (i100)",
		name: "Atma of the Scorpion",
		type: "item",
		icon: "./images/icons/atma.png",
		itemId: 7852,
		qty: 1,
		tip: "Southern Thanalan FATEs, Zenith weapon equipped.",
		options: [{ label: "FATE Completion", cost: 0, currency: "" }],
	},
	{
		id: "atma_archer",
		stage: "3. Atma (i100)",
		name: "Atma of the Archer",
		type: "item",
		icon: "./images/icons/atma.png",
		itemId: 7860,
		qty: 1,
		tip: "North Shroud FATEs, Zenith weapon equipped.",
		options: [{ label: "FATE Completion", cost: 0, currency: "" }],
	},
	{
		id: "atma_goat",
		stage: "3. Atma (i100)",
		name: "Atma of the Goat",
		type: "item",
		icon: "./images/icons/atma.png",
		itemId: 7854,
		qty: 1,
		tip: "East Shroud FATEs, Zenith weapon equipped.",
		options: [{ label: "FATE Completion", cost: 0, currency: "" }],
	},
	{
		id: "atma_maiden",
		stage: "3. Atma (i100)",
		name: "Atma of the Maiden",
		type: "item",
		icon: "./images/icons/atma.png",
		itemId: 7851,
		qty: 1,
		tip: "Central Shroud FATEs, Zenith weapon equipped. Last of the 12 Atma — completing this upgrades Zenith to Atma via 'Up in Arms'.",
		options: [{ label: "FATE Completion", cost: 0, currency: "" }],
	},

	// --- STAGE 4: Animus (i100, cosmetic glow) — 9 Trials of the Braves books ---
	{
		id: "book_skyfire_1",
		stage: "4. Animus (i100)",
		name: "Book of Skyfire I",
		type: "item",
		icon: "./images/icons/book.png",
		itemId: "EventItem:2001298",
		qty: 1,
		tip: "Buy from G'jusana, then complete: kill 10 enemies, clear 3 dungeons, 3 FATEs, and 3 levequests.",
		options: [{ label: "Poetics", cost: 100, currency: "Poetics" }],
	},
	{
		id: "book_skyfire_2",
		stage: "4. Animus (i100)",
		name: "Book of Skyfire II",
		type: "item",
		icon: "./images/icons/book.png",
		itemId: "EventItem:2001299",
		qty: 1,
		tip: "Buy from G'jusana, then complete the book's kill/dungeon/FATE/levequest tasks.",
		options: [{ label: "Poetics", cost: 100, currency: "Poetics" }],
	},
	{
		id: "book_netherfire_1",
		stage: "4. Animus (i100)",
		name: "Book of Netherfire I",
		type: "item",
		icon: "./images/icons/book.png",
		itemId: "EventItem:2001300",
		qty: 1,
		tip: "Buy from G'jusana, then complete the book's kill/dungeon/FATE/levequest tasks.",
		options: [{ label: "Poetics", cost: 100, currency: "Poetics" }],
	},
	{
		id: "book_skyfall_1",
		stage: "4. Animus (i100)",
		name: "Book of Skyfall I",
		type: "item",
		icon: "./images/icons/book.png",
		itemId: "EventItem:2001301",
		qty: 1,
		tip: "Buy from G'jusana, then complete the book's kill/dungeon/FATE/levequest tasks.",
		options: [{ label: "Poetics", cost: 100, currency: "Poetics" }],
	},
	{
		id: "book_skyfall_2",
		stage: "4. Animus (i100)",
		name: "Book of Skyfall II",
		type: "item",
		icon: "./images/icons/book.png",
		itemId: "EventItem:2001302",
		qty: 1,
		tip: "Buy from G'jusana, then complete the book's kill/dungeon/FATE/levequest tasks.",
		options: [{ label: "Poetics", cost: 100, currency: "Poetics" }],
	},
	{
		id: "book_netherfall_1",
		stage: "4. Animus (i100)",
		name: "Book of Netherfall I",
		type: "item",
		icon: "./images/icons/book.png",
		itemId: "EventItem:2001303",
		qty: 1,
		tip: "Buy from G'jusana, then complete the book's kill/dungeon/FATE/levequest tasks.",
		options: [{ label: "Poetics", cost: 100, currency: "Poetics" }],
	},
	{
		id: "book_skywind_1",
		stage: "4. Animus (i100)",
		name: "Book of Skywind I",
		type: "item",
		icon: "./images/icons/book.png",
		itemId: "EventItem:2001304",
		qty: 1,
		tip: "Buy from G'jusana, then complete the book's kill/dungeon/FATE/levequest tasks.",
		options: [{ label: "Poetics", cost: 100, currency: "Poetics" }],
	},
	{
		id: "book_skywind_2",
		stage: "4. Animus (i100)",
		name: "Book of Skywind II",
		type: "item",
		icon: "./images/icons/book.png",
		itemId: "EventItem:2001305",
		qty: 1,
		tip: "Buy from G'jusana, then complete the book's kill/dungeon/FATE/levequest tasks.",
		options: [{ label: "Poetics", cost: 100, currency: "Poetics" }],
	},
	{
		id: "book_skyearth_1",
		stage: "4. Animus (i100)",
		name: "Book of Skyearth I",
		type: "item",
		icon: "./images/icons/book.png",
		itemId: "EventItem:2001306",
		qty: 1,
		tip: "Buy from G'jusana, then complete the book's kill/dungeon/FATE/levequest tasks. Last of the 9 books — completing it finishes the Animus.",
		options: [{ label: "Poetics", cost: 100, currency: "Poetics" }],
	},

	// --- STAGE 5: Novus (i110, cosmetic) ---
	{
		id: "alexandrite",
		stage: "5. Novus (i110)",
		name: "Alexandrite",
		type: "item",
		icon: "./images/icons/alexandrite.png",
		itemId: 7883,
		qty: 75,
		tip: "Random drops from Gold-rated FATEs (Animus weapon equipped), Allied Seals (50 per unit), or Mysterious Maps (5 Alexandrite each, bought with Poetics).",
		yield: 5,
		options: [{ label: "Poetics (via Mysterious Map)", cost: 75, currency: "Poetics" }],
	},
	{
		id: "novus_materia",
		stage: "5. Novus (i110)",
		name: "Materia (any grade)",
		type: "item",
		icon: "./images/icons/materia.png",
		qty: 75,
		tip: "Melded onto the weapon as part of the Sphere Scroll infusion. Since the Novus weapon is purely cosmetic at this point, cheap low-grade materia works fine.",
		options: [{ label: "Market Board / Melding", cost: 0, currency: "" }],
	},
	{
		id: "superior_enchanted_ink",
		stage: "5. Novus (i110)",
		name: "Superior Enchanted Ink",
		type: "item",
		icon: "./images/icons/ink.png",
		itemId: 7885,
		qty: 3,
		tip: "Quest: 'Celestial Radiance' — speak to Jalzahn in Hyrstmill with Animus equipped. Buy the ink, then return with Animus unequipped to receive the Novus weapon.",
		options: [{ label: "Poetics", cost: 25, currency: "Poetics" }],
	},

	// --- STAGE 6: Nexus (i115) ---
	{
		id: "nexus_light",
		stage: "6. Nexus (i115)",
		name: "Farm 2,000 Light",
		type: "checklist",
		icon: "./images/icons/light.png",
		qty: 1,
		tip: "Quest: 'Mmmmmm, Soulglazed Relics' grants a Zodiac Glass. Accumulate 2,000 Light from FATEs, dungeons, trials, raids, and PvP (8–128 points per completion, more during bonus windows), then return to Jalzahn.",
		options: [{ label: "Light Farming", cost: 0, currency: "" }],
	},

	// --- STAGE 7: Zodiac Braves (i125) — 4 dungeon-treasure quests, done in order ---
	{
		id: "quest_ponze_of_flesh",
		stage: "7. Zodiac Braves (i125)",
		name: "'A Ponze of Flesh'",
		type: "item",
		icon: "./images/icons/treasure.png",
		qty: 1,
		tip: "First of four 'Atma 2.0' quests — collect dungeon-specific treasures instead of FATE Atma. Must be completed in order before the next quest unlocks.",
		options: [{ label: "Dungeon Treasure", cost: 0, currency: "" }],
	},
	{
		id: "quest_labor_of_love",
		stage: "7. Zodiac Braves (i125)",
		name: "'Labor of Love'",
		type: "item",
		icon: "./images/icons/treasure.png",
		qty: 1,
		tip: "Second of the four quests — more dungeon-specific treasures (Bombard Core, Sacred Spring Water, and similar).",
		options: [{ label: "Dungeon Treasure", cost: 0, currency: "" }],
	},
	{
		id: "quest_method_in_his_malice",
		stage: "7. Zodiac Braves (i125)",
		name: "'Method in His Malice'",
		type: "item",
		icon: "./images/icons/treasure.png",
		qty: 1,
		tip: "Third of the four quests — dungeon-specific treasures plus Soldiery currency.",
		options: [{ label: "Dungeon Treasure / Soldiery", cost: 0, currency: "" }],
	},
	{
		id: "quest_treasured_mother",
		stage: "7. Zodiac Braves (i125)",
		name: "'A Treasured Mother'",
		type: "item",
		icon: "./images/icons/treasure.png",
		qty: 1,
		tip: "Final of the four quests — completing it unlocks the Zodiac Braves weapon model (particle effects still locked until Zeta).",
		options: [{ label: "Dungeon Treasure", cost: 0, currency: "" }],
	},

	// --- STAGE 8: Zodiac Zeta (i135, final) ---
	{
		id: "mahatma",
		stage: "8. Zodiac Zeta (i135)",
		name: "Mahatma",
		type: "item",
		icon: "./images/icons/mahatma.png",
		qty: 12,
		tip: "Bought with Lesser Tomestones once you've banked enough Light (Nexus's Light carries forward as 'Zeta resonance'). Total across all Mahatma: roughly 2,400 tomestones and 480 Light.",
		options: [{ label: "Lesser Tomestones", cost: 200, currency: "Tomestones" }],
	},
	{
		// THIS ID MUST MATCH THE HTML LOGIC ('zeta_complete')
		id: "zeta_complete",
		stage: "8. Zodiac Zeta (i135)",
		name: "Zodiac Zeta Weapon",
		type: "checklist",
		icon: "./images/icons/zeta.png",
		qty: 1,
		tip: "Turn in every bound Mahatma to Jalzahn to finish the reforge and claim your completed Zodiac Zeta — the final stage of the ARR relic weapon!",
		tooltip: [
			"Bank Light and buy all 12 Mahatma with Lesser Tomestones",
			"Bind each Mahatma once purchased",
			"Turn in to Jalzahn for the final Zeta reforge",
		],
		options: [{ label: "Quest Complete", cost: 0, currency: "" }],
	},
];

// 10 jobs eligible for the Zodiac relic weapon line: the original ARR launch
// jobs (PLD, WAR, MNK, DRG, BRD, WHM, SCH, BLM, SMN) plus NIN, added in patch
// 2.4 while the line was still active. DRK, AST, and MCH launched in
// Heavensward (3.0) after this line was retired — they went straight to the
// Anima weapon instead, never got a Zodiac relic. GNB, SAM, RDM, DNC came
// even later.
const JOBS = [
	{ id: "PLD", label: "Paladin", role: "tank" },
	{ id: "WAR", label: "Warrior", role: "tank" },
	{ id: "WHM", label: "White Mage", role: "healer" },
	{ id: "SCH", label: "Scholar", role: "healer" },
	{ id: "MNK", label: "Monk", role: "dps" },
	{ id: "DRG", label: "Dragoon", role: "dps" },
	{ id: "NIN", label: "Ninja", role: "dps" },
	{ id: "BRD", label: "Bard", role: "dps" },
	{ id: "BLM", label: "Black Mage", role: "dps" },
	{ id: "SMN", label: "Summoner", role: "dps" },
];

const STAGE_INFO = {
	"1. Relic (i80)": "Job quest chain through Gerolt: trial, dungeon, beastmen, and four Hard-mode primals unsynced.",
	"2. Zenith (i90)": "Trade 3 Thavnairian Mist at the Furnace to reforge your relic.",
	"3. Atma (i100)": "Collect all 12 Atma from FATEs across La Noscea, Thanalan, and the Shroud.",
	"4. Animus (i100)": "Buy and clear all 9 Trials of the Braves books for a cosmetic weapon glow.",
	"5. Novus (i110)": "Meld 75 Alexandrite and 75 materia into a Sphere Scroll for another cosmetic upgrade.",
	"6. Nexus (i115)": "Farm 2,000 Light across FATEs, dungeons, trials, raids, and PvP.",
	"7. Zodiac Braves (i125)": "Clear four ordered dungeon-treasure quests — 'Atma 2.0'.",
	"8. Zodiac Zeta (i135)": "Buy 12 Mahatma with Lesser Tomestones and Light, then claim your finished Zeta weapon.",
};
